### ISSUE TITLE
Plone 6 errors out when showing listing of folderish news item

### ISSUE THREAD

**Issue by Rudd-O** [collective/collective.folderishtypes#14]
At the bottom of the news item, this shows up:

```
error while rendering collective.folderishtypes.listing_viewlet 
```

This is after creating a Folderish News Item.

The associated traceback says:

```
 - Expression: "python:portal_state.portal()"
 - Filename:   ... .egg/plone/app/contenttypes/browser/templates/listing.pt
 - Location:   (line 31: col 31)
 - Source:     tal:define="portal python:portal_state.portal();
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "listing_macro"
 - Filename:   ... egg/collective/folderishtypes/browser/listing_viewlet.pt
 - Location:   (line 4: col 32)
 - Source:     ... metal:use_macro use-macro="listing_macro">
                                              ^^^^^^^^^^^^^
 - Arguments:  template: <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7158513b9ac0>
               options: {}
               args: ()
               nothing: None
               modules: <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x715865246a00>
               request: <WSGIRequest, URL=http://127.0.1.4:8080/Rudd-O.com/en/abc/newsitem_view>
               view: <Products.Five.viewlet.metaconfigure.ListingViewlet object at 0x7158511d9670>
               context: <FolderishNewsItem at /Rudd-O.com/en/abc>
               views: <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x71585111b220>
               here: <FolderishNewsItem at /Rudd-O.com/en/abc>
               container: <FolderishNewsItem at /Rudd-O.com/en/abc>
               root: <Application at >
               traverse_subpath: []
               user: <PropertiedUser 'admin'>
               default: <DEFAULT>
               repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7158503cd140>
               loop: {}
               target_language: 'en'
               translate: <function BaseTemplate.render.<locals>.translate at 0x715850ed78b0>
               attrs: {'class': 'contentsListing'}
2021-11-30 17:52:41,023 ERROR   [plone.app.viewletmanager:114][waitress-1] Error while rendering viewlet-manager=plone.belowcontentbody, viewlet=collective.folderishtypes.listing_viewlet
Traceback (most recent call last):
  File "/home/user/optplone/buildout-cache/eggs/Chameleon-3.9.1-py3.8.egg/chameleon/template.py", line 192, in render
    self._render(stream, econtext, rcontext)
  File "/home/user/optplone/deployments/601a/var/cache/ba788d8119511059c0a6f292a5e2da3a.py", line 264, in render
    render_listing(__stream, econtext.copy(), rcontext, __i18n_domain)
  File "/home/user/optplone/deployments/601a/var/cache/ba788d8119511059c0a6f292a5e2da3a.py", line 155, in render_listing
    __m(__stream, econtext.copy(), rcontext, __i18n_domain)
  File "/home/user/optplone/deployments/601a/var/cache/1c06b63a60caedace29e6909015db0dc.py", line 472, in render_listing
    __value = _static_133670022215952('python', 'portal_state.portal()', econtext=econtext)(_static_133670022215760(econtext, __zt_tmp))
  File "/home/user/optplone/buildout-cache/eggs/zope.tales-5.1-py3.8.egg/zope/tales/pythonexpr.py", line 73, in __call__
    return eval(self._code, vars)
  File "<string>", line 1, in <module>
NameError: name 'portal_state' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/optplone/buildout-cache/eggs/plone.app.viewletmanager-3.1.2-py3.8.egg/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/user/optplone/buildout-cache/eggs/plone.app.layout-4.0.0a4-py3.8.egg/plone/app/layout/viewlets/common.py", line 78, in render
    return self.index()
  File "/home/user/optplone/buildout-cache/eggs/Zope-5.3-py3.8.egg/Products/Five/browser/pagetemplatefile.py", line 126, in __call__
    return self.__func__(__self__, *args, **kw)
  File "/home/user/optplone/buildout-cache/eggs/Zope-5.3-py3.8.egg/Products/Five/browser/pagetemplatefile.py", line 58, in __call__
    s = self.pt_render(
  File "/home/user/optplone/buildout-cache/eggs/zope.pagetemplate-4.5.0-py3.8.egg/zope/pagetemplate/pagetemplate.py", line 133, in pt_render
    return self._v_program(
  File "/home/user/optplone/buildout-cache/eggs/Zope-5.3-py3.8.egg/Products/PageTemplates/engine.py", line 365, in __call__
    return template.render(**kwargs)
  File "/home/user/optplone/buildout-cache/eggs/z3c.pt-3.3.0-py3.8.egg/z3c/pt/pagetemplate.py", line 176, in render
    return base_renderer(**context)
  File "/home/user/optplone/buildout-cache/eggs/Chameleon-3.9.1-py3.8.egg/chameleon/zpt/template.py", line 302, in render
    return super(PageTemplate, self).render(**_kw)
  File "/home/user/optplone/buildout-cache/eggs/Chameleon-3.9.1-py3.8.egg/chameleon/template.py", line 215, in render
    raise_with_traceback(exc, tb)
  File "/home/user/optplone/buildout-cache/eggs/Chameleon-3.9.1-py3.8.egg/chameleon/utils.py", line 53, in raise_with_traceback
    raise exc
  File "/home/user/optplone/buildout-cache/eggs/Chameleon-3.9.1-py3.8.egg/chameleon/template.py", line 192, in render
    self._render(stream, econtext, rcontext)
  File "/home/user/optplone/deployments/601a/var/cache/ba788d8119511059c0a6f292a5e2da3a.py", line 264, in render
    render_listing(__stream, econtext.copy(), rcontext, __i18n_domain)
  File "/home/user/optplone/deployments/601a/var/cache/ba788d8119511059c0a6f292a5e2da3a.py", line 155, in render_listing
    __m(__stream, econtext.copy(), rcontext, __i18n_domain)
  File "/home/user/optplone/deployments/601a/var/cache/1c06b63a60caedace29e6909015db0dc.py", line 472, in render_listing
    __value = _static_133670022215952('python', 'portal_state.portal()', econtext=econtext)(_static_133670022215760(econtext, __zt_tmp))
  File "/home/user/optplone/buildout-cache/eggs/zope.tales-5.1-py3.8.egg/zope/tales/pythonexpr.py", line 73, in __call__
    return eval(self._code, vars)
  File "<string>", line 1, in <module>
NameError: name 'portal_state' is not defined

 - Expression: "python:portal_state.portal()"
 - Filename:   ... .egg/plone/app/contenttypes/browser/templates/listing.pt
 - Location:   (line 31: col 31)
 - Source:     tal:define="portal python:portal_state.portal();
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "listing_macro"
 - Filename:   ... egg/collective/folderishtypes/browser/listing_viewlet.pt
 - Location:   (line 4: col 32)
 - Source:     ... metal:use_macro use-macro="listing_macro">
                                              ^^^^^^^^^^^^^
 - Arguments:  template: <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7158513b9ac0>
               options: {}
               args: ()
               nothing: None
               modules: <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x715865246a00>
               request: <WSGIRequest, URL=http://127.0.1.4:8080/Rudd-O.com/en/abc/newsitem_view>
               view: <Products.Five.viewlet.metaconfigure.ListingViewlet object at 0x7158511d9670>
               context: <FolderishNewsItem at /Rudd-O.com/en/abc>
               views: <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x71585111b220>
               here: <FolderishNewsItem at /Rudd-O.com/en/abc>
               container: <FolderishNewsItem at /Rudd-O.com/en/abc>
               root: <Application at >
               traverse_subpath: []
               user: <PropertiedUser 'admin'>
               default: <DEFAULT>
               repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7158503cd140>
               loop: {}
               target_language: 'en'
               translate: <function BaseTemplate.render.<locals>.translate at 0x715850ed78b0>
               attrs: {'class': 'contentsListing'}

```

**Comment by Rudd-O** [comment]
I have a fix:

```
<div class="contentsListing" tal:condition="view/available">
<metal:listingmacro define-macro="listing">
  <tal:block define="view nocall:context/folder_listing; listing_macro view/macros/listing">
    <metal:use_macro use-macro="listing_macro">
      <metal:empty metal:fill-slot="no_items_in_listing"></metal:empty>
    </metal:use_macro>
  </tal:block>
</metal:listingmacro>
</div>
```

is the current code.  Do this instead:

```
<div class="contentsListing" tal:condition="view/available">
<metal:listingmacro define-macro="listing">
  <tal:block define="view nocall:context/folder_listing; listing_macro view/macros/listing; portal_state context/@@plone_portal_state">
    <metal:use_macro use-macro="listing_macro">
      <metal:empty metal:fill-slot="no_items_in_listing"></metal:empty>
    </metal:use_macro>
  </tal:block>
</metal:listingmacro>
</div>
```

And, presto, it works.

**Comment by Rudd-O** [comment]
Edit: actually that doesn't work -- it shows a listing of the parent folder.  Argh.

**Comment by Rudd-O** [comment]
Strike that.  This fix works.  Will send PR.
